name: CI

on:
  # Triggers the workflow on push events but only for the develop branch
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  JEKYLL_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up the environment with Ruby 2.7 and Node 14
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v2
        with:
          path: |
            vendor/bundle
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-

      # We must explicitly set bundle install path so that it can be cached
      - name: Install Ruby dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Install Node dependencies
        run: npm install

      - name: Build website with Gulp
        run: npx gulp

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: main
